#!/usr/bin/env python

'''NAME
    slim -- Super-Lighweight Issue Manager

SYNOPSIS
    slim <option> [argument ...]

DESCRIPTION
    The slim utility reads, stores, or modifies issue and comment records.

OPTIONS

    --read
        Read an issue record.

    --write
        Write an issue record.

    --modify
        Modify an issue record.

    --help
        Display this message.

ARGUMENTS

    --id <id>
        Unique identifier for the issue.

    --date-discovered <date>
        Data the issue was first discovered.

    --version-identified <version>
        First version that identified the issue.

    --unit-test-date <date>
        Date the unit test passed.

    --code-review-date <date>
        Date the code review passed.

    --integration-test-date <date>
        Date the integration test passed.

    --system-test-date <date>
        Date the system test passed.

    --version-deployed <version>
        First version that resolves the issue.

FILES

    slim.html
        An HTML interface to slim.

    slim.sqlite3
        The SQLite3 database that stores issue and comment records.
'''
import sys
import getopt
import sqlite3

'''
Initialize the slim.sqlite3 database, if necessary.
'''
def init_db(filename):

    # open the database
    conn = sqlite3.connect('slim.sqlite3')
    cursor = conn.cursor()

    # See if table exists
    cursor.execute('''
        SELECT name FROM sqlite_master WHERE type='table' AND name='{}';
        '''.format('slim.sqlite3'))

    # Create table
    cursor.execute('''
        CREATE TABLE stocks (
            id                      text,
            date_discovered         text,
            version_identified      text,
            unit_test_date          text,
            code_review_date        text,
            integration_test_date   text,
            system_test_date        text,
            version_deployed        text)
        ''')

    return (conn, cursor)

def main():
    # parse command line options
    try:
        opts, args = getopt.getopt(sys.argv[1:], 'h', \
                                   ['help', \
                                    'read', \
                                    'write', \
                                    'modify'])
    except getopt.error, msg:
        print msg
        print 'What? Trying using --help for help.'
        sys.exit(2)
    # process options
    for o, a in opts:
        if o in ('-h', '--help'):
            print __doc__
            sys.exit(0)
        if o in ('--read'):
            print 'Read!';
        if o in ('--write'):
            print 'Write!';
        if o in ('--modify'):
            print 'Modify!';
    # process arguments
    for arg in args:
        process(arg) # process() is defined elsewhere


    (conn, cursor) = init_db('slim.sqlite3')

    # close the database
    conn.close()

if __name__ == '__main__':
    main()
